backend = "xrender";
use-damage = false;
vsync = false;

rules = (
    {
        match = "window_type = 'normal' || window_type = 'dialog'";
        opacity = 0.90;
    },

    {
        match = "window_type = 'dock' || "
                "window_type = 'desktop' || "
                "window_type = 'notification' || "
                "class_g = 'Rofi'";
        opacity = 1.0;
    }
);
